### PR TITLE
2 implement mood protocol from app

### PR DESCRIPTION
**Pull request by ibevers**
Adds a ReproSchema version of the generic and mood components of the Bridge2AI Voice data collection protocol. It is not perfect, but it is pilotable.

### CODE REVIEW

**Comment by ibevers** [comment]
Lexical mismatches with PDFs extracted using [lexical_match_reproschema_pdf.ipynb](https://github.com/sensein/b2aiprep/blob/75-lexically-match-reproschema-protocol-to-redcap-pdfs/docs/lexical_match_reproschema_pdf.ipynb)
[lexical_mismatches_unmodified.json](https://github.com/user-attachments/files/16446538/lexical_mismatches_unmodified.json)

**Comment by ibevers** [comment]
After manually comparing the above list of lexical mismatches to the RedCap pdfs, here is list fixed lexical mismatches that needs to be incorporated in to the ReproSchema files:
[lexical_mismatches_manually_reviewed.json](https://github.com/user-attachments/files/16447044/lexical_mismatches_manually_reviewed.json)

The main mismatches that are excluded for updating are:
- Entries with spaces at the end. There are many of these, and the extra space at the end is present throughout the automatically converted items.
- Long entries that were split across multiple lines and matched when manually reviewed. Not matching with entries split across multiple lines is a parsing artifact.
- Headings that are fully capitalized in the RedCap files but either have just the first letter of the first word capitalized or each word's first letter capitalized in the app. We may want to switch to all caps in the future.

**Comment by ibevers** [comment]
Screenshot 2024-08-01 at 1 59 28 PM
race_schema is undefined for some reason that I can't figure out. The link to it is working as expected.

**Comment by ibevers** [comment]
> Screenshot 2024-08-01 at 1 59 28 PM 'Race' is undefined for some reason that I can't figure out. The link to the race_schema is working as expected.
> I cannot see anything in race_schema that would indicate the source of this problem (note e's added to end of directory name temporarily as a hack to get around GitHub's cache update delay when testing in the ReproSchema UI): https://raw.githubusercontent.com/sensein/b2aiprotocol/2-implement-mood-protocol-from-app/generic/activities/q_generic_demographics/activities/required/activities/race/race_schema
> 
> See in ReproSchema UI here: https://www.repronim.org/reproschema-ui/#/activities/0?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsensein%2Fb2aiprotocol%2F2-implement-mood-protocol-from-app%2Fgeneric%2Factivities%2Fq_generic_demographics%2Factivities%2Frequired%2Factivities%2Frace%2Frace_schema

@satra do you have any insights on what might be the problem here? We have a similar issue with gender_identity.

**Comment by satra** [comment]
i would expect it to be undefined till someone has answered the question. is it still undefined after you answer it?

**Comment by satra** [comment]
looks like it is still undefined after answering. this could be a function of how variables are namespaced now. can you check the following: if you use `race_schema.race` for the isVis checks, does that work?

**Comment by ibevers** [comment]
> looks like it is still undefined after answering. this could be a function of how variables are namespaced now. can you check the following: if you use `race_schema.race` for the isVis checks, does that work?

No, now I'm getting:
Screenshot 2024-08-02 at 2 13 19 PM

**Comment by ibevers** [comment]
@satra I put it in a test protocol:
https://raw.githubusercontent.com/sensein/b2aiprotocol/2-implement-mood-protocol-from-app/generic/activities/q_generic_demographics/activities/required/activities/race/test_protocol

Getting:
Screenshot 2024-08-02 at 3 09 52 PM

**Comment by ibevers** [comment]
Oh, I need to revert your earlier suggestion,

**Comment by ibevers** [comment]
It now loads, but I'm getting another error when I click Submit. I will try updating the context file in case that could be the issue.
Screenshot 2024-08-02 at 3 23 01 PM

**Comment by ibevers** [comment]
Still had the loading problem after changing the context URL

**Comment by ibevers** [comment]
Screenshot 2024-08-02 at 4 01 49 PM

**Comment by ibevers** [comment]
## Works as expected when tested in ReproSchema UI
### Generic activities schema
#### Forms
- [ ] Demographics
- [ ] Confounders
- [ ] Voice Perception
- [ ] VHI-10
- [ ] PHQ-9
- [ ] GAD-7 Anxiety
#### Audio
- [ ] Audio check (same as mood)
- [ ] Prolonged vowel
- [ ] Maximum phonation time
- [ ] Rainbow Passage
- [ ] Glides
- [ ] Loudness
- [ ] Diadochokinesis
- [ ] Free speech
- [ ] Respiration and cough
- [ ] Picture description
- [ ] Story recall

### Mood activities schema
#### Forms
 - [ ] PANAS
 - [ ] Custom Affect Scale
 - [ ] DSM-5 Adult
 - [ ] PTSD Adult
 - [ ] ADHD Adult
 #### Audio
 - [ ] Audio check (same as mood)
 - [ ] Animal fluency
 - [ ] Open response questions

**Comment by ibevers** [comment]
Demographics issues:
- [ ] session id manually entered
- [ ] start, end, duration manually entered
- [ ] optionality of items does not match
- [ ] specify gender identity item shows when any gender item is checked
- [ ] other gender identity item shows when any gender item is checked
- [ ] gets stuck on other gender identity item

**Comment by ibevers** [comment]
Solution to gender_identity issues was change isVis conditions:
"isVis": "gender_identity === 'female' || gender_identity === 'male'"
"isVis": "gender_identity === 'other'"

to 

"['female', 'male'].includes(gender_identity)"
"['other'].includes(gender_identity)"

Not sure why this fixed it--possibly something to do with Javascript types.

**Comment by ibevers** [comment]
Not updating other to be a field in a dropdown menu for `"multipleChoice": true` items because the UI has this problem:
Screenshot 2024-08-15 at 12 21 58 PM

**Pull request merged**
